import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function getUserData() {
  const res = await fetch('https://api.github.com/users/leerob');
  // 你可以根据需要处理错误和状态码
  if (!res.ok) {
    throw new Error('Failed to fetch data');
  }
  return res.json();
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const data = await getUserData();
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="relative flex flex-col bg-background items-center">
          <Header userData={data}/>
          <main className="max-w-screen-xl w-full px-[20px] py-[40px]">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
